name: asr-env
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=2.16=mkl
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.9.9=h06a4308_0
  - cpuonly=2.0=0
  - cpython=3.10.18=py310hd8ed1ab_0
  - expat=2.7.1=h6a678d5_0
  - filelock=3.19.1=pyhd8ed1ab_0
  - gmp=6.2.1=h58526e2_0
  - gmpy2=2.1.2=py310h92f7908_0
  - intel-openmp=2025.0.0=h06a4308_1171
  - jinja2=3.1.6=pyhd8ed1ab_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libblas=3.8.0=16_mkl
  - libcblas=3.8.0=16_mkl
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=7.5.0=h14aa051_20
  - libgfortran4=7.5.0=h14aa051_20
  - libgomp=11.2.0=h1234567_1
  - liblapack=3.8.0=16_mkl
  - liblapacke=3.8.0=16_mkl
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - llvm-openmp=15.0.7=h0cdce71_0
  - markupsafe=2.1.1=py310h5764c6d_1
  - mkl=2020.2=256
  - mpc=1.2.1=h9f54685_0
  - mpfr=4.1.0=h9202a9a_1
  - mpmath=1.3.0=pyhd8ed1ab_1
  - ncurses=6.5=h7934f7d_0
  - networkx=3.4=pyhd8ed1ab_0
  - openssl=3.0.17=h5eee18b_0
  - pip=25.2=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.18=h1a3bd86_0
  - python_abi=3.10=2_cp310
  - pytorch=2.5.1=py3.10_cpu_0
  - pytorch-mutex=1.0=cpu
  - pyyaml=6.0=py310h5764c6d_4
  - readline=8.3=hc2a1206_0
  - setuptools=78.1.1=py310h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - sympy=1.14.0=pyh2585a3b_105
  - tk=8.6.15=h54e0aa7_0
  - torchaudio=2.5.1=py310_cpu
  - typing_extensions=4.15.0=pyhcf101f3_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7f98852_2
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - audioread==3.0.1
      - certifi==2025.8.3
      - cffi==2.0.0
      - charset-normalizer==3.4.3
      - click==8.3.0
      - datasets==4.1.1
      - decorator==5.2.1
      - dill==0.4.0
      - frozenlist==1.7.0
      - fsspec==2025.9.0
      - hf-xet==1.1.10
      - huggingface-hub==0.35.1
      - idna==3.10
      - jiwer==4.0.0
      - joblib==1.5.2
      - lazy-loader==0.4
      - librosa==0.11.0
      - llvmlite==0.45.0
      - msgpack==1.1.1
      - multidict==6.6.4
      - multiprocess==0.70.16
      - numba==0.62.0
      - numpy==2.2.6
      - packaging==25.0
      - pandas==2.3.2
      - platformdirs==4.4.0
      - pooch==1.8.2
      - propcache==0.3.2
      - pyarrow==21.0.0
      - pycparser==2.23
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - rapidfuzz==3.14.1
      - regex==2025.9.18
      - requests==2.32.5
      - safetensors==0.6.2
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - six==1.17.0
      - soundfile==0.13.1
      - soxr==1.0.0
      - threadpoolctl==3.6.0
      - tokenizers==0.22.1
      - tqdm==4.67.1
      - transformers==4.56.2
      - tzdata==2025.2
      - urllib3==2.5.0
      - xxhash==3.5.0
      - yarl==1.20.1
prefix: /home/mugi/miniconda3/envs/asr-env
